Repository IBM/terratorch, pull requests merged in 2025-05, with the labels that each got.

#654 Update/custom modules/example
  examples/custom_modules/alexnet.py
  terratorch/cli_tools.py
Labels: bug, 1.0.2

#663 AugmentationSequential from `torchgeo` is deprecated, trying to replace it with `kornia`
  terratorch/datamodules/biomassters.py
  terratorch/datamodules/carbonflux.py
  terratorch/datamodules/fire_scars.py
  terratorch/datamodules/forestnet.py
  terratorch/datamodules/generic_pixel_wise_data_module.py
  terratorch/datamodules/geobench_data_module.py
  terratorch/datamodules/landslide4sense.py
  terratorch/datamodules/m_SA_crop_type.py
  terratorch/datamodules/m_bigearthnet.py
  terratorch/datamodules/m_brick_kiln.py
  terratorch/datamodules/m_cashew_plantation.py
  terratorch/datamodules/m_chesapeake_landcover.py
  terratorch/datamodules/m_eurosat.py
  terratorch/datamodules/m_forestnet.py
  terratorch/datamodules/m_neontree.py
  terratorch/datamodules/m_nz_cattle.py
  terratorch/datamodules/m_pv4ger.py
  terratorch/datamodules/m_pv4ger_seg.py
  terratorch/datamodules/m_so2sat.py
  terratorch/datamodules/openearthmap.py
  terratorch/datamodules/sen1floods11.py
Labels: bug, 1.0.2

#670 Instantiation must be executed to create the object `trainer`
  terratorch/cli_tools.py
  tests/test_finetune.py
Labels: bug, 1.0.2

#666 Inference integration tests complete &updated eo v1 model paths
  integrationtests/test_base_set.py
  integrationtests/test_encoderdecoder_eo_v1_100_model_factory.yaml
  integrationtests/test_encoderdecoder_eo_v2_300_model_factory.yaml
  integrationtests/test_encoderdecoder_eo_v2_600_model_factory.yaml
Labels: tests, 1.0.2

#672 Rename the image and label greps to tif wildcard
  terratorch/cli_tools.py
Labels: enhancement, studio

#673 Specialized tests for prediction.
  tests/test_finetune.py
Labels: tests

#675 Adapting multimodal dataset to support empty label roots.
  terratorch/cli_tools.py
  terratorch/datamodules/generic_multimodal_data_module.py
  terratorch/datasets/generic_multimodal_dataset.py
Labels: bug, 1.0.2

#680 Basic Configuration to use Pre-commit
  .pre-commit-config.yaml
  docs/contributing.md
  pyproject.toml
Labels: enhancement, 1.0.2

#645 Fix predict and tiled inference
  .github/workflows/test.yaml
  docs/inference.md
  mkdocs.yml
  terratorch/datasets/generic_multimodal_dataset.py
  terratorch/datasets/generic_pixel_wise_dataset.py
  terratorch/tasks/tiled_inference.py
  tests/resources/configs/manufactured-finetune_prithvi_eo_v1_100.yaml
  tests/resources/configs/manufactured-finetune_prithvi_eo_v2_600.yaml
  tests/resources/configs/manufactured-finetune_prithvi_swin_L.yaml
  tests/resources/configs/manufactured-finetune_terramind_v1_base.yaml
Labels: enhancement, 1.0.2

#686 Fixing `pre-commit` configuration.
  .pre-commit-config.yaml
Labels: 1.0.2

#660 Add add object detection to TerraTorch around torchvision-detection
  .gitignore
  docs/dataset_table.md
  examples/confs/object_detection_substation_prithvi.yaml
  examples/confs/object_detection_substation_resnet50.yaml
  examples/confs/object_detection_vhr10_Clay.yaml
  examples/confs/object_detection_vhr10_prithvi.yaml
  examples/confs/object_detection_vhr10_resnet50.yaml
  examples/confs/object_detection_vhr10_vit.yaml
  pyproject.toml
  terratorch/datamodules/__init__.py
  terratorch/datamodules/m_VHR10.py
  terratorch/datamodules/substation.py
  terratorch/datasets/__init__.py
  terratorch/datasets/m_VHR10.py
  terratorch/datasets/substation.py
  terratorch/models/__init__.py
  terratorch/models/backbones/dofa_vit.py
  terratorch/models/necks.py
  terratorch/models/object_detection_model_factory.py
  terratorch/models/pixel_wise_model.py
  terratorch/registry/timm_registry.py
  terratorch/tasks/__init__.py
  terratorch/tasks/object_detection_task.py
  tests/test_object_detection_factory.py
  tests/test_object_detection_task.py
Labels: enhancement, 1.1

#560 Testing for python 3.13
  .github/workflows/pylint.yml
  .github/workflows/test.yaml
  pyproject.toml
  tests/test_backbones.py
  tests/test_clay_tasks.py
  tests/test_datasets.py
  tests/test_encoder_decoder_torchgeo_models.py
  tests/test_finetune.py
  tests/test_generic_dataset.py
  tests/test_multi_source_registry.py
  tests/test_prithvi_model_factory.py
Labels: 1.1

#355 Added support for temporal segmentation data in encoder decoder factory
  terratorch/models/encoder_decoder_factory.py
  tests/test_temporal_wrapper.py
Labels: enhancement, 1.1

#699 Update tiled inference
  terratorch/tasks/base_task.py
  terratorch/tasks/reconstruction_tasks.py
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  terratorch/tasks/tiled_inference.py
Labels: enhancement, 1.1

#690 Periodical documentation synchronization with `main`
  docs/backbones.md
  docs/contributing.md
  docs/tutorials/adding_custom_modules.md
  mkdocs.yml
  terratorch/models/backbones/terramind/model/terramind.py
Labels: documentation, 1.1
