Repository IBM/terratorch, pull requests merged in 2025-03, with the labels that each got.

#477 timm must be bounded in some way
  pyproject.toml
Labels: bug, 0.99.9

#463 pinning albumentations==1.4.6
  pyproject.toml
Labels: 0.99.9

#458 Removing hardcoded paths.
  examples/confs/dofa_sen1floods11_fcn.yaml
  examples/confs/granite-wxc-merra2-downscale-small-config.yaml
  examples/confs/wxc-gravity-wave-ccc.yaml
Labels: 0.99.9

#471 Fixing issues with `interpolate_pos_encoding` in prithvi
  terratorch/models/backbones/prithvi_mae.py
  terratorch/models/backbones/prithvi_vit.py
Labels: 0.99.9

#454 ModelCheckpoint must be defined in the config dict, not during the parsing.
  terratorch/cli_tools.py
  tests/resources/configs/manufactured-finetune_prithvi_eo_v2_300.yaml
Labels: bug, 0.99.9

#468 Dealing with encoder outputs with dimension > 3 when using the reshaper neck.
  terratorch/models/necks.py
  tests/resources/configs/manufactured-finetune_satlas_upernet.yaml
Labels: bug, 0.99.9

#469 Removing unnecessary steps and passing extra arguments for tiled inference
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  terratorch/tasks/tiled_inference.py
Labels: bug, 0.99.9

#484 Adding badges for the README
  README.md
Labels: 1.0

#491 Update WxCTutorialDownscaling.ipynb for terratorch 0.99.9 support
  examples/notebooks/WxCTutorialDownscaling.ipynb
Labels: 1.0

#464 Skipping automatic tests when the modifications are for documentation and other files outside the core.
  .github/workflows/test.yaml
Labels: 1.0

#489 add release scripts
  pyproject.toml
  release/pin_dependencies.py
  release/release.py
  release/requirements_release.txt
Labels: 1.0

#495 Badge for coverage
  README.md
  assets/coverage-badge.svg
Labels: enhancement, 1.0

#459 Basic support for visualizing models (as graphs)
  examples/notebooks/Visualize_model.ipynb
  pyproject.toml
  terratorch/utils.py
Labels: 1.0

#498 Improve/tests
  .github/workflows/test.yaml
  pyproject.toml
  tests/test_finetune.py
Labels: enhancement, 1.0

#494 Updating the tests workflows to install granitewxc and prithviwxc from PyPI.
  .github/workflows/test.yaml
Labels: enhancement, 1.0

#502 Removing unnecessary module
  terratorch/datasets/sen1floods11_lat_lon.py
Labels: 1.0

#483 allow users to run iterate using terratorch command
  docs/quick_start.md
  terratorch/__main__.py
Labels: enhancement, 1.0

#501 Update cli_tools.py, make subcommand optional
  terratorch/cli_tools.py
Labels: 1.0

#509 graph break fix
  terratorch/models/necks.py
Labels: bug, 1.0

#457 Trying to solve issues with UNet and ASPPHeads.
  terratorch/models/backbones/unet.py
  terratorch/models/decoders/aspp_head.py
  terratorch/models/decoders/utils.py
  terratorch/tasks/classification_tasks.py
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  tests/test_decoders.py
Labels: 1.0

#518 Added tutorial files
  examples/tutorial/README.md
  examples/tutorial/configs/prithvi_v2_eo_300_tl_unet_burnscars.yaml
  examples/tutorial/configs/prithvi_v2_eo_300_tl_unet_multitemporal_crop.yaml
  examples/tutorial/configs/prithvi_v2_eo_300_tl_unet_sen1floods11.yaml
  examples/tutorial/prithvi_v2_eo_300_tl_unet_burnscars.ipynb
  examples/tutorial/prithvi_v2_eo_300_tl_unet_multitemporal_crop.ipynb
  examples/tutorial/prithvi_v2_eo_300_tl_unet_sen1floods11.ipynb
Labels: 1.0

#508 Options to directly informing kwargs for backbones and decoders
  terratorch/models/encoder_decoder_factory.py
Labels: bug, 1.0

#500 Adjust in the checkpoint adjuster script
  examples/scripts/fix_backwards_compatibility.py
Labels: 1.0

#478 Automatically running tiled inference for the `test` step when memory is insufficient.
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  tests/resources/configs/manufactured-finetune_prithvi_swin_B_segmentation.yaml
Labels: bug, stakeh-paolo, 1.0

#534 Handling many possibilities when trying to perform the test step with support for tiled inference
  terratorch/tasks/base_task.py
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  tests/resources/configs/manufactured-finetune_prithvi_eo_v2_600_segmentation_tiled.yaml
Labels: 1.0

#535 Update README to support browser dark themes.
  README.md
  assets/logo_white.png
Labels: 1.0

#538 improve_wxc_import_error_handling
  terratorch/models/__init__.py
  terratorch/models/wxc_model_factory.py
Labels: 1.0

#542 Correct number of bands for single band (as for segmentation) output file.
  terratorch/cli_tools.py
Labels: bug, 1.0

#540 More tests for TorchGeo ViT and Resnet backbones.
  terratorch/models/backbones/__init__.py
  tests/test_backbones.py
  tests/test_encoder_decoder_torchgeo_models.py
Labels: 1.0, tests

#526 Yaml schema file v2.0
  examples/confs/yaml_schema.yaml
Labels: 1.1

#548 Explicitly save only the best model
  terratorch/cli_tools.py
  tests/resources/configs/manufactured-finetune_prithvi_eo_v2_300.yaml
Labels: enhancement, 1.0

#550 support / accept contributions according to MIT license
  LICENSE
  README.md
Labels: 1.0

#559 Add test for LoRA and update PEFT requirement
  pyproject.toml
  terratorch/models/peft_utils.py
  tests/test_encoder_decoder_model_factory.py
Labels: 1.1
