Repository IBM/terratorch, pull requests merged in 2025-01, with the labels that each got.

#328 201modularize wxc
  examples/notebooks/WxCTutorialGravityWave.ipynb
  integrationtests/test_prithvi_wxc_model_factory.py
  terratorch/datamodules/era5.py
  terratorch/models/backbones/select_patch_embed_weights.py
  terratorch/models/pincers/unet_pincer.py
  terratorch/models/wxc_model_factory.py
  terratorch/tasks/wxc_gravity_wave_task.py
  terratorch/tasks/wxc_task.py
Labels: 1.0

#365 Testing the repository using the installation from pyproject for torchgeo models.
  .github/workflows/test.yaml
  pyproject.toml
Labels: 1.0

#377 Refactor prithvi
  .github/workflows/test.yaml
  docs/quick_start.md
  docs/registry.md
  examples/confs/burn_scars.yaml
  examples/confs/burnscars_smp.yaml
  examples/confs/eurosat.yaml
  examples/confs/forestnet_timm.yaml
  examples/confs/multi_temporal_crop.yaml
  examples/confs/multimae_sen1floods11.yaml
  examples/confs/multimodal_prithvi_sen1floods11.yaml
  examples/confs/sen1floods11_vit.yaml
  examples/confs/sen1floods11_vit_dual_lr.yaml
  examples/confs/sen1floods11_vit_local_ckpt.yaml
  examples/confs/sen1floods11_vit_mmseg.yaml
  examples/confs/sen1floods11_vit_peft.yaml
  examples/confs/sen1floods11_vit_smp.yaml
  examples/confs/sen4agri.yaml
  examples/confs/sen4map_ViT-L.yaml
  examples/confs/smp_model_factory.yaml
  examples/notebooks/Tutorial.ipynb
  examples/scripts/instantiate_satmae_backbone.py
  examples/scripts/open_local_model.py
  requirements/required.txt
  terratorch/io/file.py
  terratorch/models/backbones/dofa_vit.py
  terratorch/models/backbones/prithvi_mae.py
  terratorch/models/backbones/prithvi_vit.py
  terratorch/models/backbones/select_patch_embed_weights.py
  tests/resources/configs/manufactured-finetune_prithvi_eo_v1_100.yaml
  tests/resources/configs/manufactured-finetune_prithvi_swin_B_segmentation.yaml
  tests/resources/configs/manufactured-finetune_prithvi_vit_100.yaml
  tests/test_backbones.py
  tests/test_finetune.py
  tests/test_prithvi_vit.py
Labels: 1.0, reviewing

#347 add smoke.py and an integration tests folder getting picked up by the IBM Research GPU cluster atm
  integrationtests/test_smoke.py
Labels: 1.0

#380 add cli support for wxc gravity wave
  examples/confs/wxc-gravity-wave-ccc.yaml
  examples/confs/wxc-gravity-wave.yaml
  terratorch/cli_tools.py
  terratorch/datamodules/__init__.py
  terratorch/models/wxc_model_factory.py
  terratorch/tasks/__init__.py
  terratorch/tasks/wxc_task.py
Labels: 1.0, reviewed

#330 Feat: Implement multiple test dataloaders in all tasks
  terratorch/tasks/base_task.py
  terratorch/tasks/classification_tasks.py
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
Labels: 1.0

#336 Feat: Add `compute_statistics` subcommand
  terratorch/cli_tools.py
  terratorch/utils.py
Labels: 1.0

#378 Freeze/head/decoder
  requirements/required.txt
  terratorch/models/pixel_wise_model.py
  terratorch/models/scalar_output_model.py
  terratorch/tasks/base_task.py
  terratorch/tasks/classification_tasks.py
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  tests/resources/configs/manufactured-finetune_prithvi_swin_B.yaml
Labels: 0.99.8

#389 consolidate requirements
  .github/workflows/test.yaml
  pyproject.toml
  requirements/dev.txt
  requirements/optional.txt
  requirements/required.txt
  requirements/test.txt
Labels: 0.99.8
