Repository IBM/terratorch, pull requests merged in 2025-09, with the labels that each got.

#731 Add TerraMind tiny and small
  terratorch/models/backbones/terramind/README.md
  terratorch/models/backbones/terramind/model/generate.py
  terratorch/models/backbones/terramind/model/terramind_generation.py
  terratorch/models/backbones/terramind/model/terramind_register.py
  terratorch/models/backbones/terramind/model/terramind_tim.py
  terratorch/models/backbones/terramind/model/terramind_vit.py
  terratorch/models/backbones/terramind/tokenizer/models/uvit.py
  terratorch/models/backbones/terramind/tokenizer/tokenizer_register.py
  terratorch/models/backbones/terramind/tokenizer/vqvae.py
  terratorch/tasks/multilabel_classification_tasks.py
Labels: 1.1

#840 improve verbosity on tests
  pyproject.toml
Labels: 1.1

#835 Updating dependabot rules
  .github/dependabot.yaml
Labels: 1.1

#860 Trying to enforce the latest version of torchgeo
  pyproject.toml
Labels: bug, 1.1, uv

#893 Remove pytest and pytest-sugar from pyproject.toml
  pyproject.toml
Labels: 1.1.1

#894 Restoring downloads counter
  README.md
Labels: 1.1.1
