Repository IBM/terratorch, pull requests merged in 2025-04, with the labels that each got.

#527 Add linear decoder and check `includes_head` at decoder level first
  terratorch/models/decoders/__init__.py
  terratorch/models/decoders/linear_decoder.py
  terratorch/models/encoder_decoder_factory.py
  terratorch/registry/mmseg_registry.py
  terratorch/registry/registry.py
  terratorch/registry/smp_registry.py
  tests/test_decoders.py
  tests/test_encoder_decoder_model_factory.py
Labels: 1.1, reviewing

#562 Special case when callbacks is empty and checkpointing is enabled.
  terratorch/cli_tools.py
Labels: bug

#567 Guaranteeing that the checkpointing operations are understood by Lightning
  terratorch/cli_tools.py
Labels: bug, 1.0.1

#568 Fix for issue 565
  terratorch/cli_tools.py
  terratorch/tasks/segmentation_tasks.py
  tests/resources/configs/manufactured-finetune_prithvi_swin_B_segmentation.yaml
Labels: enhancement, 1.0.1

#573 An attempt of reducing the cost of testing by simplifying the list of tests.
  tests/resources/configs/manufactured-finetune_prithvi_eo_v2_300.yaml
  tests/resources/configs/manufactured-finetune_prithvi_eo_v2_600_segmentation_tiled.yaml
  tests/resources/configs/manufactured-finetune_prithvi_swin_B_segmentation.yaml
  tests/test_finetune.py
  tests/test_prithvi_tasks.py
Labels: tests, 1.0.1

#577 Update DOFA Backbone for Arbitrary Image Sizes
  examples/confs/object_detection_vhr10_DOFA.yaml
  terratorch/models/backbones/dofa_vit.py
Labels: enhancement, 1.1

#593 [Refactor] Improve dataset class structure and plotting options
  terratorch/datasets/generic_multimodal_dataset.py
  terratorch/datasets/generic_pixel_wise_dataset.py
  terratorch/datasets/open_sentinel_map.py
  terratorch/datasets/pastis.py
  terratorch/datasets/sen4agrinet.py
Labels: enhancement, 1.0.1

#528 Implement ViT-Adapter
  terratorch/models/backbones/detr_ops/README.md
  terratorch/models/backbones/detr_ops/functions/__init__.py
  terratorch/models/backbones/detr_ops/functions/ms_deform_attn_func.py
  terratorch/models/backbones/detr_ops/modules/__init__.py
  terratorch/models/backbones/detr_ops/modules/ms_deform_attn.py
  terratorch/models/backbones/prithvi_mae.py
  terratorch/models/backbones/prithvi_vit.py
  terratorch/models/backbones/prithvi_vit_adapter.py
  terratorch/models/backbones/vit_adapter_modules.py
  terratorch/models/decoders/unet_decoder.py
  terratorch/models/pixel_wise_model.py
  tests/test_backbones.py
Labels: 1.1, reviewing

#595 Integrate ECCC downscaling WxC Model
  examples/confs/eccc_downscaling_conv.yaml
  examples/confs/eccc_downscaling_unet.yaml
  examples/notebooks/WxCTutorialDownscalingECCC.ipynb
  terratorch/datamodules/eccc.py
  terratorch/models/wxc_model_factory.py
  terratorch/tasks/eccc_downscaling_task.py
Labels: enhancement, 1.0.1

#594 Removing undesirable variables from deploy config
  terratorch/cli_tools.py
Labels: bug, 1.0.1

#579 Using lists to define instructions about how to output predictions
  terratorch/cli_tools.py
  terratorch/tasks/segmentation_tasks.py
  tests/resources/configs/manufactured-finetune_prithvi_swin_B_segmentation.yaml
Labels: enhancement, 1.0.1

#601 Update get_common_prefix to handle cases where len(prefix_list) < 1
  terratorch/datasets/multi_temporal_crop_classification.py
  terratorch/models/backbones/select_patch_embed_weights.py
Labels: bug, reviewing, 1.0.1

#578 Recording metrics to a CSV file
  terratorch/tasks/base_task.py
  terratorch/tasks/classification_tasks.py
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  tests/resources/configs/manufactured-finetune_prithvi_eo_v2_600_segmentation_tiled.yaml
Labels: enhancement, 1.0.1

#584 bug fix: invalid index error when users run `terratorch` command
  terratorch/__main__.py
Labels: bug, 1.0.1

#605 add Dockerfile
  Dockerfile
Labels: 1.0.1

#606 A better way to remove the prefix `model.` from some old checkpoints.
  terratorch/cli_tools.py
Labels: bug, 1.0.1

#607 Predownload model configs
  pyproject.toml
  terratorch/__main__.py
  terratorch/cli_tools.py
Labels: 1.0.1

#608 improve code readability and clearity
  terratorch/tasks/tiled_inference.py
Labels: 1.0.1

#614 fix broken link in prithvi_v2_eo_300_tl_unet_burnscars.ipynb
  examples/tutorials/PrithviEOv2/prithvi_v2_eo_300_tl_unet_burnscars.ipynb
Labels: 1.0.1

#616 fix predict mode in generic_pixel_wise_data_module.py
  terratorch/datamodules/generic_pixel_wise_data_module.py
Labels: 1.0.1

#449 [WIP] Add full model registry
  examples/confs/multimae_sen1floods11.yaml
  terratorch/datamodules/generic_multimodal_data_module.py
  terratorch/datasets/generic_multimodal_dataset.py
  terratorch/datasets/utils.py
  terratorch/models/__init__.py
  terratorch/models/backbones/multimae/criterion.py
  terratorch/models/backbones/multimae/multimae.py
  terratorch/models/backbones/multimae_register.py
  terratorch/models/backbones/prithvi_mae.py
  terratorch/models/backbones/prithvi_vit.py
  terratorch/models/full_model_factory.py
  terratorch/models/model.py
  terratorch/registry/__init__.py
  terratorch/registry/registry.py
  terratorch/tasks/__init__.py
  terratorch/tasks/classification_tasks.py
  terratorch/tasks/multilabel_classification_tasks.py
  terratorch/tasks/reconstruction_tasks.py
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  tests/resources/configs/manufactured-reconstruction_prithvi_eo_v1_100.yaml
  tests/test_backbones.py
  tests/test_prithvi_tasks.py
  tests/test_prithvi_vit.py
  tests/test_reconstructions.py
Labels: enhancement, 1.0.1

#618 pinning SMP to 0.4.0
  pyproject.toml
Labels: bug, 1.0.1

#617 Imagefolder/dummy tiff file
  pyproject.toml
  terratorch/datasets/generic_scalar_label_dataset.py
  tests/datamodules/test_genericscalarlabeldatamodule.py
  tests/datamodules/utils.py
Labels: bug, 1.0.1

#615 Improve/custom modules
  examples/alexnet_custom_model.py
  examples/confs/alexnet_custom_model_config.yaml
  examples/custom_modules/__init__.py
  examples/custom_modules/alexnet.py
  terratorch/cli_tools.py
Labels: 1.0.1

#633 Updating examples to use the latest terratorch version
  examples/tutorials/PrithviEOv2/prithvi_v2_eo_300_tl_unet_agb.ipynb
  examples/tutorials/PrithviEOv2/prithvi_v2_eo_300_tl_unet_burnscars.ipynb
  examples/tutorials/PrithviEOv2/prithvi_v2_eo_300_tl_unet_multitemporal_crop.ipynb
Labels: bug

#623 docs: Add tutorial for custom modules
  docs/tutorials/adding_custom_modules.md
Labels: documentation

#625 Generic factory and updated example for custom modules
  examples/alexnet_custom_model.py
  examples/confs/alexnet_custom_model_config.yaml
  examples/custom_modules/alexnet.py
  terratorch/models/__init__.py
  terratorch/models/generic_model_factory.py
Labels: enhancement, 1.0.2

#641 Cleaning pip cache for GH runners
  .github/workflows/test.yaml
Labels: tests, 1.0.2

#639 Dealing with cases in which the prediction is a tuple(tuple, str)
  terratorch/cli_tools.py
Labels: bug, 1.0.2

#630 We don't need to run the tests when a notebook is changed
  .github/workflows/test.yaml
Labels: tests

#635 Periodical synchronization for the documentation.
  docs/backbones.md
  docs/changelog.md
  docs/model_factories.md
  docs/tutorials/adding_custom_modules.md
  mkdocs.yml
  terratorch/models/backbones/torchgeo_resnet.py
  terratorch/models/backbones/torchgeo_swin_satlas.py
  terratorch/models/backbones/torchgeo_vit.py
  terratorch/models/generic_model_factory.py
Labels: documentation

#529 Implement VPT for Prithvi and Clay
  terratorch/models/backbones/clay_v1/embedder.py
  terratorch/models/backbones/clay_v1/modules.py
  terratorch/models/backbones/prithvi_mae.py
  terratorch/models/backbones/prithvi_vit.py
  terratorch/registry/timm_registry.py
  tests/test_prithvi_tasks.py
Labels: 1.1

#637 The stackability tests weren't disableable for segmentation
  terratorch/datamodules/generic_pixel_wise_data_module.py
  terratorch/datamodules/generic_scalar_label_data_module.py
Labels: bug, 1.0.2

#646 A way to avoid the list of mask files be emtpy
  terratorch/datasets/generic_pixel_wise_dataset.py
Labels: bug, 1.0.2

#648 Ignoring tests when examples are updated
  .github/workflows/test.yaml
Labels: tests

#651 Updating test config templates
  integrationtests/test_encoderdecoder_eo_v2_100_model_factory.yaml
  integrationtests/test_encoderdecoder_eo_v2_300_model_factory.yaml
  integrationtests/test_encoderdecoder_eo_v2_600_model_factory.yaml
  integrationtests/test_encoderdecoder_timm_resnet34_model_factory.yaml
  integrationtests/test_prithvi_swinB_model_factory_config.yaml
  integrationtests/test_prithvi_swinL_model_factory_config.yaml
  integrationtests/test_smp_resnet34_model_factory_config.yaml
  integrationtests/test_template.py
  integrationtests/test_template_config.yaml
Labels: tests

#644 The classification ground truth should be `int`, shouldn't it?
  terratorch/tasks/classification_tasks.py
Labels: bug, 1.0.2
