Repository IBM/terratorch, pull requests merged in 2025-08, with the labels that each got.

#779 Trying to avoid the device be returned as negative
  terratorch/tasks/tiled_inference.py
Labels: bug

#785 Update integration tests
  integrationtests/configs/test_encoder_decoder_timm_resnet101_model_factory.yaml
  integrationtests/configs/test_encoder_decoder_timm_resnet152_model_factory.yaml
  integrationtests/configs/test_encoder_decoder_timm_resnet18_model_factory.yaml
  integrationtests/configs/test_encoder_decoder_timm_resnet34_model_factory.yaml
  integrationtests/configs/test_encoder_decoder_timm_resnet50_model_factory.yaml
  integrationtests/configs/test_encoderdecoder_clay_v1_base_model_factory.yaml
  integrationtests/configs/test_encoderdecoder_timm_convnext_large-fb-in22k_model_factory.yaml
  integrationtests/configs/test_encoderdecoder_timm_convnext_xlarge-fb-in22k_model_factory.yaml
  integrationtests/test_base_set.py
Labels: 1.1

#800 Missing dependencies for deploying documentation
  .github/workflows/docs.yaml
Labels: documentation

#783 Add test for multimodal datamodule
  terratorch/datamodules/generic_multimodal_data_module.py
  terratorch/datasets/generic_multimodal_dataset.py
  terratorch/tasks/regression_tasks.py
  tests/resources/configs/manufactured-finetune_terramind_v1_base.yaml
  tests/resources/inputs/regression_test_0_input.tif
  tests/resources/inputs/regression_test_0_label.tif
  tests/resources/inputs/regression_test_1_input.tif
  tests/resources/inputs/regression_test_1_label.tif
  tests/resources/inputs/segmentation_test_0_input.tif
  tests/resources/inputs/segmentation_test_0_label.tif
  tests/resources/inputs/segmentation_test_1_input.tif
  tests/resources/inputs/segmentation_test_1_label.tif
  tests/resources/inputs/segmentation_test_2_input.tif
  tests/resources/inputs/segmentation_test_2_label.tif
  tests/resources/inputs/segmentation_test_3_input.tif
  tests/resources/inputs/segmentation_test_3_label.tif
  tests/test_finetune.py
  tests/test_generic_dataset.py
Labels: 1.1

#802 Configuring environment to push to github.io
  .github/workflows/docs.yaml
Labels: documentation
