Repository IBM/terratorch, pull requests merged in 2025-06, with the labels that each got.

#656 unpack sequential scheduler
  terratorch/datasets/transforms.py
  terratorch/models/smp_model_factory.py
  terratorch/tasks/optimizer_factory.py
  tests/test_optimizer_factory.py
  tests/test_smp_model_factory.py
Labels: 1.2

#713 add missing import: from torchmetrics.wrappers import ClasswiseWrapper
  terratorch/tasks/multilabel_classification_tasks.py
Labels: bug

#733 Update class-wise metric names
  terratorch/tasks/classification_tasks.py
  terratorch/tasks/multilabel_classification_tasks.py
  terratorch/tasks/segmentation_tasks.py
Labels: 1.1
