Repository IBM/terratorch, pull requests merged in 2025-07, with the labels that each got.

#753 Squeezing ground truth with innapropriate formats
  terratorch/tasks/segmentation_tasks.py
Labels: bug, 1.0.3

#742 Fix/custom modules
  examples/alexnet_custom_model_config.yaml
Labels: tutorial, 1.0.3

#766 Fixing dependencies installation during tests
  .github/workflows/test.yaml
Labels: bug

#769 Label grep still needs be informed in the prediction mode
  terratorch/datamodules/generic_pixel_wise_data_module.py
Labels: bug

#729 tiled inference on validation
  terratorch/tasks/base_task.py
  terratorch/tasks/regression_tasks.py
  terratorch/tasks/segmentation_tasks.py
  terratorch/tasks/tiled_inference.py
Labels: 1.1

#676 Updates for TerraMind
  terratorch/models/backbones/terramind/model/generate.py
  terratorch/models/backbones/terramind/model/modality_info.py
  terratorch/models/backbones/terramind/model/terramind.py
  terratorch/models/backbones/terramind/model/terramind_generation.py
  terratorch/models/backbones/terramind/model/terramind_register.py
  terratorch/models/backbones/terramind/model/terramind_tim.py
  terratorch/models/backbones/terramind/model/terramind_vit.py
  terratorch/models/backbones/terramind/tokenizer/models/vit_models.py
  terratorch/models/backbones/terramind/tokenizer/text/__init__.py
  terratorch/models/backbones/terramind/tokenizer/text/text_tokenizer.py
  terratorch/models/backbones/terramind/tokenizer/tokenizer_register.py
  terratorch/models/backbones/terramind/tokenizer/vqvae.py
  tests/test_backbones.py
  tests/test_reconstructions.py
Labels: 1.1
